server:
  port: 8765  # Zuul 서버 포트번호 (localhost:8765/??????) 
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: api-gateway

zuul:
  routes:
    tiger:      # 2. Eureka에 등록된 서비스인 service01로 가라
      path: /app/** # 1. 이렇게 입력이 되면 (localhost:8765/app)
      #service-id: Service01
      strip-prefix: false
      
    tiger2:      # 2. Eureka에 등록된 서비스인 service02로 가라
      path: /bpp/** # 1. 이렇게 입력이 되면 (localhost:8765/bpp)
      #service-id: Service02
      strip-prefix: false

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka